// Generated by CoffeeScript 1.9.3
d3.json('http://localhost:5001/api/v0/object/get?arg=/ipfs/QmPE6xb88LKNkwptiAsKNQ2Tryd8S8r9CBs1t9fSdXh9cY', function(ipfsData) {
  var toggleAll;
  this.root = {
    Name: "links",
    children: ipfsData.Links
  };
  this.root.x0 = h / 2;
  this.root.y0 = 0;
  toggleAll = function(d) {
    if (d.children) {
      d.children.forEach(toggleAll);
      return toggle(d);
    }
  };
  this.root.children.forEach(toggleAll);
  return update(this.root);
});
